### ISSUE TITLE
[Suggestion] Serene Seasons support

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/berry-good#30]
Requesting support for Serene Seasons [https://www.curseforge.com/minecraft/mc-mods/serene-seasons](url) by including sweet berry pips in the Spring/Summer/Autumn item tags, thank you.

**Comment by Cicopath** [comment]
You can use a datapack to include any modded items for Serene Seasons. There's a downloadable .zip in the Serene Seasons Discord for this.

**Comment by MarioSMB** [comment]
If one had to do that for every mod's items seasons would not be worth the trouble. But I know the Abnormals policy, it's very likely this won't change, unfortunately.

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/berry-good/commit/b87467e230e0ab3ea1e0cdcb27ab6eec9067ced0
