### ISSUE TITLE
World loading stops in splash screen [MC 1.19.1] [Forge 42.0.1] [BerryGood 6.0.0]

### ISSUE THREAD

**Issue by DancerVlt69** [team-abnormals/berry-good#31]
Loading a (saved) world stops with the splash screen: 'Error in currently selected data packs prevent...'
[latest.log](https://github.com/team-abnormals/savage-and-ravage/files/9225694/latest.log)
[debug.log](https://github.com/team-abnormals/buzzier-bees/files/9225737/debug.log)

The same  with *_Neapolitan_* and *_Savage 'n Ravage_*

**Comment by bageldotjpg** [comment]
Yes, the mod does not work on 1.19.1, as marked on CurseForge. A change was made to music discs.

**Comment by DancerVlt69** [comment]
> Yes, the mod does not work on 1.19.1, as marked on CurseForge. A change was made to music discs.

Ok, good to know. At the moment i hate the permanent changes on/in (the) Forge (-Loader)
