### ISSUE TITLE
1.15 version doesn't work with latest 1.15 forge. [Solved]

### ISSUE THREAD

**Issue by WaldoTheRanger** [team-abnormals/berry-good#8]
None of the features work. Bushes are placed with the berries just like in vanilla, and the crafting recipe is non-existent
Tested by itself using multi-mc

Log:
[ConsoleLog.txt](https://github.com/minecraftabnormals/Berry-Good/files/4963340/ConsoleLog.txt)

**Comment by bageldotjpg** [comment]
I'm gonna need more, exact Forge version, latest.log, etc. I'm going to immediatly assume this is either an issue with MultiMC or with any other mods you have because I've used this mod several times in 1.15, in the Twitch launcher and the vanilla launcher.

**Comment by WaldoTheRanger** [comment]
My bad:
[LatestLog.txt](https://github.com/minecraftabnormals/Berry-Good/files/4966189/LatestLog.txt)
Forge version 31.2.0
I guess I meant latest recommended version.

**Comment by WaldoTheRanger** [comment]
I'm somewhat new to this whole process, what did you mean by etc?

**Comment by bageldotjpg** [comment]
Well... I'm not seeing anything wrong... it looks like its loading the mod and doesn't give errors relating to it. I'd try update to latest Forge though, not recommended.

**Comment by WaldoTheRanger** [comment]
So it turns out I'm just an idiot.
I remembered that I have some issues with accidentally renaming files during my mass download session for my modpack.
so I opened up the jar file for your mod, and was greeted with the asset files for elanai dodge.

Thanks for your time. Sorry I wasted it.
